// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbqlomzeavtyjycmnncv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxicWxvbXplYXZ0eWp5Y21ubmN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MTk0NDAsImV4cCI6MjA2Njk5NTQ0MH0.HXe09wlUjDEqU8gG5Ufdm42VSfAhahkmnEbV0XMwYYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});